# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_exhaustivetree_wrappers", use_symbols = TRUE, package_name = "exhaustivetree")

#' @docType package
#' @usage NULL
#' @useDynLib exhaustivetree, .registration = TRUE
NULL

rust_exhaustive_tree <- function(x_robj, gamma_robj, depth) .Call(wrap__rust_exhaustive_tree, x_robj, gamma_robj, depth)

