# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_parallelpolicytree_wrappers", use_symbols = TRUE, package_name = "parallelpolicytree")

#' @docType package
#' @usage NULL
#' @useDynLib parallelpolicytree, .registration = TRUE
NULL

rust_exhaustive_tree <- function(x_robj, gamma_robj, depth) .Call(wrap__rust_exhaustive_tree, x_robj, gamma_robj, depth)

rust_predict <- function(r_tree_mat, x_robj) .Call(wrap__rust_predict, r_tree_mat, x_robj)

